# Generated by Django 5.0.4 on 2024-05-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_edit_blog', 'can_comment'),)},
        ),
    ]
